version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aeromagdalena-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/aeromagdalena
      SPRING_DATASOURCE_USERNAME: aeromagdalena
      SPRING_DATASOURCE_PASSWORD: aeromagdalena123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWT_SECRET: mysecretJ7Q16xGQkmEbE3fv4ecEmDkT5k3TkZZFg6srLt2YmpkEtjPfS28F3u
      APP_JWT_EXPIRATION_MS: 43200000
    depends_on:
      - db
    networks:
      - aeromagdalena_network

  db:
    image: postgres:16
    container_name: aeromagdalena-db
    environment:
      POSTGRES_DB: aeromagdalena
      POSTGRES_USER: aeromagdalena
      POSTGRES_PASSWORD: aeromagdalena123
    ports:
      - "5432:5432"
    volumes:
      - aeromagdalena_db_data:/var/lib/postgresql/data
    networks:
      - aeromagdalena_network

volumes:
  aeromagdalena_db_data:

networks:
  aeromagdalena_network:
    driver: bridge
