spring.application.name=aeromagdalena
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aeromagdalena}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:aeromagdalena}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aeromagdalena123}
server.port=${SERVER_PORT:8081}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

app.jwt.secret=${APP_JWT_SECRET:mysecretJ7Q16xGQkmEbE3fv4ecEmDkT5k3TkZZFg6srLt2YmpkEtjPfS28F3u}
app.jwt.expirationMs=${APP_JWT_EXPIRATION_MS:43200000}
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true